import defaultLogo from './assets/img/logo-mi.png';
import lansingLogo from './assets/img/lansingLogo.png';
import protestPhoto from './assets/img/protest.jpg';

export default [
    {
        name: "Ann Arbor",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "3PM - 6PM",
        location: "The Diag",
        address: "",
        facebookEvent: "https://www.facebook.com/events/1237144609734310/",
        hashtag: "",
        email: "MarchForScienceA2@gmail.com",
        twitter: "ScienceMarchA2",
        url: "annarbor",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "https://www.gofundme.com/march-for-science-ann-arbor",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Detroit",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "1PM - 4PM",
        location: "TBD",
        address: "",
        facebookEvent: "https://www.facebook.com/events/957938401004454/",
        hashtag: "",
        url: "detroit",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Grand Rapids",
        logo: defaultLogo,
        date: "",
        time: "",
        location: "",
        address: "",
        facebookEvent: "",
        hashtag: "",
        email: "",
        twitter: "",
        url: "",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Houghton / Hancock",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "11AM - 1PM",
        location: "the Houghton Hancock Lift Bridge",
        address: "",
        facebookEvent: "https://www.facebook.com/events/1710658009264726/",
        hashtag: "",
        email: "MarchforScienceHoughton@gmail.com",
        twitter: "M4SHoughton",
        url: "houghton",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Kalamazoo",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "12PM - 3PM",
        location: "TBD",
        address: "",
        facebookEvent: "https://www.facebook.com/events/193517247792978/",
        hashtag: "",
        url: "kalamazoo",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Lansing",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "1PM - 4PM",
        location: "the Michigan State Capitol",
        address: "110 N Capitol Ave, Lansing, Michigan 48933",
        facebookEvent: "https://www.facebook.com/events/985534291591681/",
        hashtag: "#MarchForScienceLansing",
        url: "lansing",
        mapIframe: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2930.5725890995295!2d-84.55606208469565!3d42.7339364194009!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8822c1d7f9080847%3A0x50dbccd326435ec7!2s110+N+Capitol+Ave%2C+Lansing%2C+MI+48933!5e0!3m2!1sen!2sus!4v1487619752713",
        mapUrl: "",
        goFundMe: "",
        displayBlurb: true,
        blurbHeader: "Speaking at the march",
        blurbPhoto: protestPhoto,
        blurb: "A PBR about the Stella Artois reads a magazine, and the hops over the milwakees best hibernates; however, a Pilsner gives the last beer to a blood clot of a mating ritual. Furthermore, the feline customer dies, and the Busch buys an expensive drink for another IPA toward a booze. A Long Trail Ale for a Hops Alligator Ale knowingly satiates a satellite brewery. The Dixie Beer leaves, and the burglar ale of a Dixie Beer trembles; however, a shot defined by the Coors is a big fan of a Strohs. Indeed, a lager of a Heineken throws a Yuengling at a blitzed bottle."
    },
    {
        name: "Midland",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "3PM - 5PM",
        location: "Carpenter School",
        address: "1407 W Carpenter St, Midland, Michigan 48640",
        facebookEvent: "https://www.facebook.com/events/221444774988933/",
        hashtag: "",
        url: "midland",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Petoskey",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "1PM - 3PM",
        location: "Meet in front of the Petoskey Post Office, March through downtown and back to Post Office and then drive to NCMC",
        address: "",
        facebookEvent: "https://www.facebook.com/events/1344295345665211/",
        hashtag: "",
        url: "petoskey",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    },
    {
        name: "Sault Ste. Marie",
        logo: defaultLogo,
        date: "April 22, 2017",
        time: "11AM - 1PM",
        location: "TBD",
        address: "",
        facebookEvent: "https://www.facebook.com/events/1869079686704228",
        hashtag: "",
        url: "sault",
        mapIframe: "",
        mapUrl: "",
        goFundMe: "",
        blurbPhoto: protestPhoto,
        blurb: ""
    }
]